version: "3.0"

expectations:
  population_size: 1000

actions:
  query:
    run: >
      sqlrunner:latest
        --dummy-data-file output/generate_dummy_rows/dummy_rows.csv.gz
        --output output/query/rows.csv.gz
        analysis/query.sql
    outputs:
      highly_sensitive:
        rows: output/query/rows.csv.gz

  aggregate:
    needs: [query]
    run: python:latest python -m analysis.aggregate
    outputs:
      moderately_sensitive:
        aggregates: output/aggregate/*_by_*.csv.gz

  plot:
    needs: [aggregate]
    run: python:latest python -m analysis.plot
    outputs:
      moderately_sensitive:
        plots: output/plot/*.png
