version: "3.0"

expectations:
  population_size: 1000

actions:
  query:
    run: >
      sqlrunner:latest
        --dummy-data-file analysis/dummy_rows.csv.gz
        --output output/query/rows.csv.gz
        --log-file output/query/log.json
        analysis/query.sql
    outputs:
      highly_sensitive:
        rows: output/query/rows.csv.gz
      moderately_sensitive:
        log: output/query/log.json

  aggregate:
    needs: [query]
    run: python:latest python -m analysis.aggregate
    outputs:
      moderately_sensitive:
        aggregates: output/aggregate/*_by_*.csv

  plot_from_2016:
    needs: [aggregate]
    run: >
      python:latest python -m analysis.plot
        --from-date 2016-01-01
        --output output/plot_from_2016
    outputs:
      moderately_sensitive:
        plots: output/plot_from_2016/*.png

  plot_from_2020:
    needs: [aggregate]
    run: >
      python:latest python -m analysis.plot
        --from-date 2020-02-01
        --output output/plot_from_2020
    outputs:
      moderately_sensitive:
        plots: output/plot_from_2020/*.png

  plot_from_last_30_days:
    needs: [aggregate]
    run: >
      python:latest python -m analysis.plot
        --from-offset 30
        --output output/plot_from_last_30_days
    outputs:
      moderately_sensitive:
        plots: output/plot_from_last_30_days/*.png

  render_report:
    needs: [query, plot_from_2016, plot_from_2020, plot_from_last_30_days]
    run: python:latest python -m analysis.render_report
    outputs:
      moderately_sensitive:
        report: output/render_report/report.html
